export default {
    CART_ITEM_INCREMENT: "CART_ITEM_INCREMENT",
    CART_ITEM_DECREMENT: "CART_ITEM_DECREMENT",
    START_FETCH_BLOG_LIST: "START_FETCH_BLOG_LIST",
    FETCH_BLOG_LIST_SUCCESS: "FETCH_BLOG_LIST_SUCCESS",
    FETCH_BLOG_LIST_FAIL: "FETCH_BLOG_LIST_FAIL",
    MARK_NOTIFICATION_AS_READ_BY_ID: 'MARK_NOTIFICATION_AS_READ_BY_ID',
    MARK_ALL_NOTIFICATIONS_AS_READ: 'MARK_ALL_NOTIFICATIONS_AS_READ',
    START_NOTIFICATION_POST: 'START_NOTIFICATION_POST',
    FINISH_NOTIFICATION_POST: 'FINISH_NOTIFICATION_POST',
    RECIVED_NOTIFICATIONS: 'RECIVED_NOTIFICATIONS',
    START_LOGIN: 'START_LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    CHANGE_AVATAR: 'CHANGE_AVATAR'
}