export default {
    CART_ITEM_INCREMENT:"CART_ITEM_INCREMENT",
    CART_ITEM_DECREMENT:"CART_ITEM_DECREMENT",
    START_FETCH_BLOG_LIST:"START_FETCH_BLOG_LIST",
    FETCH_BLOG_LIST_SUCCESS:"FETCH_BLOG_LIST_SUCCESS",
    FETCH_BLOG_LIST_FAIL:"FETCH_BLOG_LIST_FAIL"
}